### ISSUE TITLE
Some additions for data and tools

### ISSUE THREAD

**Issue by jwoLondon** [tjukanovt/30DayMapChallenge#1]
Not sure if you prefer PRs or issues for suggested changes/additions, so am starting with an issue to log some proposed additions...

_Under Data:_

---

[OS OpenData](https://www.ordnancesurvey.co.uk/opendatadownload/products.html)

Ordnance Survey Open Data for Great Britain. Includes general topographic map data at a range of scales; useful thematic data such as greenspace, terrain, roads and rivers; postcode and place name georeferencing.

---

_Under Tools:_

---

[Mapshaper](https://mapshaper.org)

Useful for geospatial data processing in the browser such as file format conversion, map projection, feature simplification, filtering, clipping, merging etc. Can also be run [locally from the command line](https://github.com/mbloch/mapshaper).

[Vega-Lite](https://vega.github.io/vega-lite/) 

Declarative visualization specification including [cartographic output](https://vega.github.io/vega-lite/examples/#maps-geographic-displays). Specifications can be written directly in JSON or via program language interfaces such as [altair](https://altair-viz.github.io) (Python) and [elm-vegalite](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite) (Elm). See, for example, this tutorial on using [OpenStreetMap with elm-vegalite](https://github.com/gicentre/litvis/blob/master/documents/tutorials/geoTutorials/openstreetmap.md)

[Vega](https://vega.github.io/vega/)

More flexible but lower-level declarative visualization specification including cartographic output. Specifications can be written directly in JSON or via program language interfaces such [elm-vega](https://package.elm-lang.org/packages/gicentre/elm-vega/latest/).

[Litvis](https://github.com/gicentre/litvis)

Literate Visualization notebook environment optimised for specifying visualizations and documenting the design process. While not specific to cartography, can be a useful environment for exploring cartographic design.

[Observable](https://observablehq.com)

Reactive notebook environment for generation of visualization and cartographic output embedded in a textual narrative. Focus is on using [d3](https://d3js.org) for specifying visual output.

---

**Comment by tjukanovt** [comment]
Both are very welcome! Thank you!

**Comment by tjukanovt** [comment]
Added to main readme
