### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by christopherkettell** [tjukanovt/30DayMapChallenge#10]
Is the 30 day map challenge to get its own logo? 

Logos mean stickers 👍

**Comment by Namora** [comment]
@christopherkettell  what colours are we talking about? (...asking for a friend)

**Comment by Namora** [comment]
@christopherkettell @tjukanovt - still a work in progress, let me know what you think. 
![image](https://user-images.githubusercontent.com/14276941/143539560-b22a30c8-1290-41dc-9957-a494f3b2b984.png)

**Comment by tjukanovt** [comment]
Wow! Thanks for opening the issue and thanks @Namora for drafting some awesome logo ideas. Stickers and logo have been on my to-do list for a while now. I made a few suggestions for color palettes with an [online tool](https://www.canva.com/colors/color-palette-generator/) from my own maps. I think option 3 could work with the simplistic design and maybe 1 or 2 would express the playfulness of the challenge. Thoughts?

**Option 1**
![image](https://user-images.githubusercontent.com/13899537/143549690-49083be2-db3d-4135-b538-fdc9e0bcf59b.png)
```
Cararra: #ECE9E5
Minsk: #363789
Hokey Pokey: #D3A82C
Persian Red: #CC2E2D
```

**Option 2**
![image](https://user-images.githubusercontent.com/13899537/143549855-6604b438-6837-4b4a-942a-683bed254e0f.png)
```
Mountain Meadow: #16AD9C
Melanie: #DCAACD
Buttercup: #F5C017
Medium Red Violet: #AB2A95
```

**Option 3**
![image](https://user-images.githubusercontent.com/13899537/143550642-0118ab9c-7d83-49b9-aa4d-e9916b3cbcf7.png)
```
Soft Peach: #F2E6EB
Outer Space: #2A3234
Boulder: #7C7474
Empress: #806C76
```

**Comment by Namora** [comment]
Yes! I love it, will apply and send through soonest. Will work on a couple
fun sticker ideas as well. Keep well.

**Comment by HeikkiVesanto** [comment]
I like 1 and 3 (top left and top right).

But the capitalisation should follow the hashtag? #30DayMapChallenge. Line the middle bottom.

I would buy some stickers.

**Comment by Namora** [comment]
@tjukanovt I did not forget about the logo. Busy checking contrast (for digital side of things) and will try and get the closest print colours to the ones you supplied. Started on a more "serious" sticker.

@HeikkiVesanto thanks for the feedback regarding upper and lowercase, I applied that change. 

Screenshot in the meantime. Have a fabulous Monday everyone! 
![image](https://user-images.githubusercontent.com/14276941/143868732-7095a41f-0d6c-41d5-8a89-b732853c1c5d.png)

**Comment by tjukanovt** [comment]
@Namora Looks great! Are you interested in doing a PR to the repo with SVG files with the design? I will try to do a few designs myself too for tomorrows metamapping day.

**Comment by Namora** [comment]
@tjukanovt I have NO Idea how to create a "PR" ... it wanted me to compare things...That is where I stopped. :) I have SVGs you are more than welcome to work on. Let me know how I should upload them for you.

**Comment by tjukanovt** [comment]
@Namora No worries! What if you zip them and attach in this issue?

**Comment by Namora** [comment]
@tjukanovt tried that.  Screenshot below. 
Try this:
https://we.tl/t-EbDVdRETpD

![image](https://user-images.githubusercontent.com/14276941/143878190-e90ef8df-7a50-414a-91d0-c70e018c8c30.png)

**Comment by Namora** [comment]
@tjukanovt  "Add file"...I feel silly now. Thanks, glad it worked - saw it in the code section.

**Comment by tjukanovt** [comment]
@Namora No problem. And thanks again!

**Comment by tjukanovt** [comment]
@Namora Just double-checking: it is ok for you if I use your design in stickers etc. promoting the challenge and maybe modify it further if needed? I'd like to at least credit you properly, so do you have a name / username which I should give the credits to? 🤗

**Comment by Namora** [comment]
@tjukanovt check your mail - I sent a message via your website form. :)

**Comment by christopherkettell** [comment]
and I bought some stickers :D amazing!
