### ISSUE TITLE
Add Python packages for the Tools section?

### ISSUE THREAD

**Issue by HTenkanen** [tjukanovt/30DayMapChallenge#19]
Hi @tjukanovt, just saw that you seem to list R packages for geospatial / visualization. I was wondering that would it be useful to list a few useful libraries for Python as well?

**Comment by tjukanovt** [comment]
Hey @HTenkanen! Absolutely! You probably have a **_slightly_** better view on the relevant Python packages at the moment than I do, so would you like to open a PR about adding some?

**Comment by HTenkanen** [comment]
Sure, I can help out. :)
